version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_todo_data:/var/lib/mysql
    networks:
      - todonet

  mailtrap:
    image: maildev/maildev:latest
    container_name: todo-mailtrap
    ports:
      - "1080:1080"   # Web interface (Mailtrap UI)
      - "1025:1025"   # SMTP port
    environment:
      - MAILDEV_INCOMING_USER=mailtrap
      - MAILDEV_INCOMING_PASS=mailtrap

volumes:
  mysql_todo_data:

networks:
  todonet:
    name: todonet
